### ISSUE TITLE
Does not display the indicated pattern correctly

### ISSUE THREAD

**Issue by UnEnanoMas** [Ifera/ScoreHud#172]
https://streamable.com/a2mmpr

```yml
# Set the title for the scoreboard shown.
titles:
  # If *true* then 'titles.lines' will be used for showing changing
  # or flickering titles. Although fancy but they might cause lag
  # so be your own judge. This may also cause the scoreboard to
  # flicker at times. (not preferred)
  #
  # If *false* then 'titles.title' will be used for showing a simple
  # title on the scoreboard. (preferred)
  flicker: true

  # If 'titles.flicker' is set to true then adjust the rate at which
  # the titles should change. In seconds.
  # Default: 5 (seconds)
  period: 1

  # A simple title that will be displayed for scoreboard.
  title: "§l§b☆§fDivine§gAngels§b☆"

  # Changing titles. Add as many as you desire.
  lines:
  - "§l§8☆§fD§7ivine§gAngels§8☆"
  - "§l§b☆§fDi§7vine§gAngels§b☆"
  - "§l§8☆§fDiv§7ine§gAngels§8☆"
  - "§l§b☆§fDivi§7ne§gAngels§b☆"
  - "§l§8☆§fDivin§7e§gAngels§8☆"
  - "§l§b☆§fDivine§7§gAngels§b☆"
  - "§l§b☆§fDivine§7§eA§gngels§b☆"
  - "§l§8☆§fDivine§7§eAn§ggels§8☆"
  - "§l§b☆§fDivine§7§eAng§gels§b☆"
  - "§l§8☆§fDivine§7§eAnge§gls§8☆"
  - "§l§b☆§fDivine§7§eAngel§gs§b☆"
  - "§l§8☆§fDivine§7§eAngels§8☆"
  - "§l§b☆§fD§ei§fv§ei§fn§ee§fA§en§fg§ee§fl§es§b☆"
  - "§l§8☆§eD§fi§ev§fi§en§fe§eA§fn§eg§fe§el§fs§8☆"
  ```
  
  Is skipping many
  
  (Dev 59)
