### ISSUE TITLE
Read the cooldogdev comment, idk what im saying

### ISSUE THREAD

**Issue by MrBlasyMSK** [Ifera/ScoreHud#198]
Apparently there is a problem when scorehud tries to update too fast and has changed the value, I have no idea why it happens, so if you need more help to solve this read and talk to cooldogdev who seems to understand it.

https://github.com/cooldogedev/BedrockEconomy/issues/67#issuecomment-1076745404

And I'm sure this also affects VanishV2 in the player update, since the dev says it can't find what's wrong with the code.

This is my ScoreHud config
```yml
---
# DO NOT EDIT THIS VALUE.
# ONLY FOR INTERNAL USE.
scorehud-version: 3

# Set the title for the scoreboard shown.
titles:
  # If *true* then 'titles.lines' will be used for showing changing
  # or flickering titles. Although fancy but they might cause lag
  # so be your own judge. This may also cause the scoreboard to
  # flicker at times. (not preferred)
  #
  # If *false* then 'titles.title' will be used for showing a simple
  # title on the scoreboard. (preferred)
  flicker: true

  # If 'titles.flicker' is set to true then adjust the rate at which
  # the titles should change. In seconds.
  # Default: 5 (seconds)
  period: 1
  ```
  
  In case you need it:
  PHP: 8.0.16
  PMMP Version: 4.2.4
  OS: linux
  ScoreHud Version: Dev78
